### ISSUE TITLE
`Failed to create a GLFW window with any profile`

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/PrismLauncher#10]
### Version of Prism Launcher

<details>
<summary>Logs:</summary>

```
[00:48:56] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[00:48:56] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[00:48:56] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.5
[00:48:56] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.4
[00:48:56] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.3
[00:48:56] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.2
[00:48:56] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.1
[00:48:56] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.0
[00:48:56] [main/INFO] [EARLYDISPLAY/]: Trying GL version 3.3
[00:48:56] [main/INFO] [EARLYDISPLAY/]: Trying GL version 3.2
[00:48:56] [main/ERROR] [EARLYDISPLAY/]: Failed to find any valid GLFW profile. Trying 4.6: GLFW error: [0x10009]GLX: Failed to find a suitable GLXFBConfig
[00:48:56] [main/ERROR] [EARLYDISPLAY/]: ERROR DISPLAY
Failed to initialize graphics window with current settings.


Failure details:
Failed to find a valid GLFW profile.
We tried 4.6, 4.5, 4.4, 4.3, 4.2, 4.1, 4.0, 3.3, 3.2 but none of them worked.
Trying 4.6: GLFW error: [0x10009]GLX: Failed to find a suitable GLXFBConfig
Trying 4.5: GLFW error: [0x10009]GLX: Failed to find a suitable GLXFBConfig
Trying 4.4: GLFW error: [0x10009]GLX: Failed to find a suitable GLXFBConfig
Trying 4.3: GLFW error: [0x10009]GLX: Failed to find a suitable GLXFBConfig
Trying 4.2: GLFW error: [0x10009]GLX: Failed to find a suitable GLXFBConfig
Trying 4.1: GLFW error: [0x10009]GLX: Failed to find a suitable GLXFBConfig
Trying 4.0: GLFW error: [0x10009]GLX: Failed to find a suitable GLXFBConfig
Trying 3.3: GLFW error: [0x10009]GLX: Failed to find a suitable GLXFBConfig
Trying 3.2: GLFW error: [0x10009]GLX: Failed to find a suitable GLXFBConfig

If you click yes, we will try and open https://links.minecraftforge.net/early-display-errors in your default browser
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133)
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53)
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19)
	... 8 more
Caused by: java.lang.IllegalStateException: Failed to create a GLFW window with any profile
	at SECURE-BOOTSTRAP/net.minecraftforge.earlydisplay@1.20.4-49.1.0/net.minecraftforge.fml.earlydisplay.DisplayWindow.initWindow(DisplayWindow.java:439)
	at SECURE-BOOTSTRAP/net.minecraftforge.earlydisplay@1.20.4-49.1.0/net.minecraftforge.fml.earlydisplay.DisplayWindow.start(DisplayWindow.java:293)
	at SECURE-BOOTSTRAP/net.minecraftforge.earlydisplay@1.20.4-49.1.0/net.minecraftforge.fml.earlydisplay.DisplayWindow.initialize(DisplayWindow.java:155)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.1.0/net.minecraftforge.fml.loading.ImmediateWindowHandler.load(ImmediateWindowHandler.java:49)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.1.0/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.earlyInitialization(ModDirTransformerDiscoverer.java:43)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:144)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:73)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17)
	at net.minecraftforge.bootstrap@2.1.0/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188)
	... 15 more
Exiting with ERROR
Process exited with code 2.
```
</details>

Complete logs: [logs.txt.gpg.zip](https://github.com/user-attachments/files/16117558/logs.txt.gpg.zip)

+3

### Version of Qt

Not read.

### Description of bug

Not read.

### Steps to reproduce

Not read.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Benjamin-Loison** [comment]
Very likely related to [Benjamin_Loison/Debian/issues/21#issuecomment-2079956](https://codeberg.org/Benjamin_Loison/Debian/issues/21#issuecomment-2079956).

Note that I updated while playing if I remember correctly, but at some point the game crashed and the previous logs happened when I tried restarting.

Restarting the computer very probably solves this issue.

**Comment by Benjamin-Loison** [comment]
```bash
sudo flatpak update -y
```
<details>
<summary>Output:</summary>

```
Looking for updates…


        ID                                                        Branch             Op             Remote             Download
 1. [✓] org.freedesktop.Platform.GL.nvidia-535-183-01             1.4                i              flathub            342.6 MB / 342.6 MB

Installation complete.
```
</details>

solves the issue.

**Comment by Benjamin-Loison** [comment]
```bash
sudo flatpak update -y
```
<details>
<summary>Output:</summary>

```
Looking for updates…


        ID                       Branch      Op  Remote   Download
 1. [✓] org.kde.Platform.Locale  5.15-23.08  u   flathub  17.9 kB / 394.3 MB
 2. [✓] org.kde.Platform.Locale  6.6         u   flathub  17.9 kB / 393.2 MB
 3. [✓] org.kde.Platform.Locale  6.7         u   flathub   1.6 kB / 393.2 MB
 4. [✓] org.kde.Platform         6.6         u   flathub  22.4 MB / 332.2 MB
 5. [✓] org.kde.Platform         6.7         u   flathub  25.8 MB / 333.8 MB
 6. [✓] org.kde.Platform         5.15-23.08  u   flathub   8.7 MB / 340.5 MB

Updates complete.
```
</details>

solves the issue.

**Comment by Benjamin-Loison** [comment]
Restarting Prism Launcher solved the issue following `sudo flatpak update -y` it seems.
